version: '3.3'
services:
  web:
    #We want to build a custom image
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php73

    depends_on: 
      - db
    
    #attach a local directory to the container
    volumes:
      - ./php:/var/www/html
    ports:
#80 is the default port provided by the container (when you install apache somewhere, it's exposed at port 80). and 8000 is the port exposed for the host (your machine).
     - 8000:80
  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    depends_on: 
      - db
    ports:
     - 8080:80
